#!/usr/bin/python
# This file is part of jobs-admin.
# Copyright 2010 Jacob Peddicord <jpeddicord@ubuntu.com>
#
# jobs-admin is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# jobs-admin is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with jobs-admin.  If not, see <http://www.gnu.org/licenses/>.

# i18n
import locale
import gettext
locale.setlocale(locale.LC_ALL, '')
gettext.install('jobs-admin', '/usr/share/locale', unicode=True)

import gtk
from dbus.mainloop.glib import DBusGMainLoop
from JobsAdmin.gtk import JobsAdminUI

DBusGMainLoop(set_as_default=True)

ui = JobsAdminUI()
ui.load_jobs()
ui.win_main.show_all()

gtk.main()
