#!/usr/bin/python

import gtk
from dbus.mainloop.glib import DBusGMainLoop
from JobsAdmin import JobsAdminUI

DBusGMainLoop(set_as_default=True)

ui = JobsAdminUI()
ui.load_jobs()
ui.win_main.show_all()

gtk.main()
